{
 "title": "08 - Application performance monitoring ( APM )",
 "tags": [
  "tempo",
  "tracing",
  "apm"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "Grafana" },
   { "name": "tempo", "query": "tempo" },
   { "name": "mimir", "query": "prometheus" },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_bucket,service)"
    }
   },
   { "name": "span_kind", "query": "SPAN_KIND_SERVER" },
   {
    "name": "span_name",
    "label": "span_name",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_bucket{service=\"$service\", span_kind=\"$span_kind\"},span_name)"
    }
   },
   { "name": "PXX", "label": "Percentile", "query": "50" },
   { "name": "comparsion", "query": "1m" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.${PXX}, sum(rate(traces_spanmetrics_latency_bucket{service=\"${service}\", span_kind=~\"${span_kind}\", span_name=~\"${span_name}\"}[$__rate_interval])) by (le, service)) * 1000",
     "legendFormat": "Latency"
    },
    {
     "expr": "histogram_quantile(.${PXX}, sum(rate(traces_spanmetrics_latency_bucket{service=\"${service}\", span_kind=~\"${span_kind}\", span_name=~\"${span_name}\"}[$__rate_interval]  offset ${comparsion} )) by (le, service)) * 1000",
     "legendFormat": "Comparsion"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.5, sum(rate(traces_spanmetrics_latency_bucket{service=\"${service}\", span_name=~\"${span_name}\"}[$__rate_interval])) by (le)) * 1000\n",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"${service}\", span_name=~\"${span_name}\"}[$__rate_interval])) by (le)) * 1000\n",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Throughput is measured in transactions per minute (tpm).",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(service) (round(increase(traces_spanmetrics_calls_total{service=\"${service}\",span_kind=~\"${span_kind}\", span_name=~\"${span_name}\"}[1m:1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service) (round(increase(traces_spanmetrics_calls_total{service=\"${service}\",span_kind=~\"${span_kind}\", span_name=~\"${span_name}\"}[1m:1m] offset ${comparsion} )))",
     "legendFormat": "B"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"${service}\", span_name=~\"${span_name}\"}[$__rate_interval])) by (le)) * 1000\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Failed transaction rate",
   "type": "timeseries",
   "description": "The percentage of failed transactions for the selected service. HTTP server transactions with a 4xx status code (client error) aren't considered failures because the caller, not the server, caused the failure.",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service) (round(increase(traces_spanmetrics_calls_total{service=\"${service}\",span_kind=~\"${span_kind}\", span_name=~\"${span_name}\", status_code=\"STATUS_CODE_ERROR\"}[1m:1m]))) / sum by(service) (round(increase(traces_spanmetrics_calls_total{service=\"${service}\",span_kind=~\"${span_kind}\", span_name=~\"${span_name}\"}[1m:1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service) (round(increase(traces_spanmetrics_calls_total{service=\"${service}\",span_kind=~\"${span_kind}\", span_name=~\"${span_name}\",status_code=\"STATUS_CODE_ERROR\"}[1m:1m] offset ${comparsion} ))) / sum by(service) (round(increase(traces_spanmetrics_calls_total{service=\"${service}\",span_kind=~\"${span_kind}\", span_name=~\"${span_name}\"}[1m:1m] offset ${comparsion} )))",
     "legendFormat": "B"
    }
   ]
  },
  {
   "title": "Tracing Samping",
   "type": "table",
   "description": "Max data point: 20",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 19 },
   "targets": [
    {
     "filters": [
      { "id": "6215c8fc", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "datahub-service" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "/datahub/api/v2/graphql/query" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"${service}\" && name=~\"${span_name}\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}