{
 "title": "07 - Lunch Choice Simulator",
 "description": "RD Sharing demo =)",
 "tags": [
  "demo",
  "lgtm"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "suggester",
    "label": "Suggester Name",
    "query": "Ray Wang : person-1,Lee Shie : person-2,James Lu : person-3,Ben Liu : person-4"
   },
   {
    "name": "food",
    "label": "Food Name",
    "query": {
     "query": "label_values(ikala_lunch_decision_count{suggester=~\"$suggester\"},food)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://i0.wp.com/ikala.ai/wp-content/uploads/2020/06/cropped-ikala-app-icon-2.png?fit=512%2C512&ssl=1\" alt=\"iKala Logo\">\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "options": {
    "content": "# Lunch Choice Simulator\n---\nWhen we are at iKala, the biggest challenge we face is deciding what to eat for lunch with our colleagues or can we survive in falling elevator.\nTo simulate this issue, we have created the demo simulator. This demo service includes the following APIs:\n- `[POST] /lunch-suggestion/:food` : Simulates the lunch decision-making process. You will receive the outcome of the decision.\n- `[GET] /lunch-decision/:food` : Represents your colleague who will give you their decision about the lunch option you provided."
   }
  },
  {
   "title": "Top 5 Preferred Team Lunch Choices",
   "type": "table",
   "description": "Displays the top 5 most preferred lunch choices by the team, pulled from Prometheus datasource. Supports filters for specific suggester and food.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum(ikala_lunch_decision_count{decision=\"agree\", suggester=~\"$suggester\", food=~\"$food\"}) by (food))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suggestion Count by Team Member",
   "type": "bargauge",
   "description": "Displays a visual breakdown of lunch suggestions made by each user. Useful for observing user participation over time in the lunch decision-making process.",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (suggester) (rate(ikala_lunch_decision_count{suggester=~\"$suggester\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lunch Decision Count",
   "type": "stat",
   "description": "This panel displays the count of lunch decisions made, grouped based on the suggester and type of food. It allows for tracking trends and understanding most popular choices.",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (span_name) (traces_spanmetrics_calls_total{span_name=\"/lunch-suggestion/:food\", service=~\"$suggester\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lunch Decision Count Rate Chart",
   "type": "piechart",
   "description": "This tool displays data on lunch decisions made over time as a pie chart, allowing for easy tracking of meal suggestion frequency.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (decision) (rate(ikala_lunch_decision_count{suggester=~\"$suggester\", food=~\"$food\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Foods Mentioned Trend Analysis",
   "type": "timeseries",
   "description": "This panel provides a trend analysis on food suggestions, measuring how often each food item is proposed over a given time interval. It employs Prometheus as a datasource.",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (food) (ikala_lunch_decision_count{suggester=~\"$suggester\", food=~\"$food\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 }, "options": { "content": "---\n---" } }
 ]
}