{
 "title": "06 - Lunch Choice Simulator Real-Time Interactive UI",
 "description": "live demo for rd-sharing.",
 "tags": [
  "demo",
  "rd-sharing",
  "canvas"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 19, "x": 0, "y": 0 }, "options": { "content": "### \n# LUNCH TIME ......" } },
  { "title": "Next Page", "type": "text", "description": "Link to grafana dashboard", "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 }, "options": { "content": "---" } },
  {
   "type": "canvas",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum((count_over_time({compose_service=\"person-1\"} |= `Majority vote: Yes.`[$__auto])) or vector(0)) -\nsum((count_over_time({compose_service=\"person-1\"} |= `Majority vote: No.`[$__auto]))or vector(0))"
    }
   ]
  },
  {
   "title": "Ray Wang Conversation Record",
   "type": "logs",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "{compose_service=\"person-1\"} | json | __error__=\"\"  |  line_format \" > {{.message}}\""
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum((count_over_time({compose_service=\"person-2\"} |= `Majority vote: Yes.`[$__auto])) or vector(0)) -\nsum((count_over_time({compose_service=\"person-2\"} |= `Majority vote: No.`[$__auto]))or vector(0))"
    }
   ]
  },
  {
   "title": "Lee Shie Conversation Record",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "{compose_service=\"person-2\"} | json | __error__=\"\"  |  line_format \" > {{.message}}\""
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "canvas",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum((count_over_time({compose_service=\"person-3\"} |= `Majority vote: Yes.`[$__auto])) or vector(0)) -\nsum((count_over_time({compose_service=\"person-3\"} |= `Majority vote: No.`[$__auto]))or vector(0))"
    }
   ]
  },
  {
   "title": "James Lu Conversation Record",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "{compose_service=\"person-3\"} | json | __error__=\"\"  |  line_format \" > {{.message}}\""
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum((count_over_time({compose_service=\"person-4\"} |= `Majority vote: Yes.`[$__auto])) or vector(0)) -\nsum((count_over_time({compose_service=\"person-4\"} |= `Majority vote: No.`[$__auto]))or vector(0))"
    }
   ]
  },
  {
   "title": "Ben Liu Conversation Record",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "{compose_service=\"person-4\"} | json | __error__=\"\"  |  line_format \" > {{.message}}\""
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 }, "options": { "content": "---" } }
 ]
}